name: CI

on:
  push:
    branches:
      - main
      - development
      - feature/reports
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        id: run-tests
        run: mvn test

      - name: Generate Surefire Report
        if: always()
        run: mvn surefire-report:report

      - name: Archive all test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-test-reports
          path: target/surefire-reports
          retention-days: 5
          if-no-files-found: warn


  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy
        run: echo "Deploying..."

  report:
    if: failure()
    needs: [ test, deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Download all test reports
        uses: actions/download-artifact@v3
        with:
            name: all-test-reports
            path: target/surefire-reports

      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          name: all-test-reports
          path: target/surefire-reports

      - name: Extract failed test reports
        run: |
          for report in $(find target/surefire-reports -name '*.txt'); do
            if grep -q 'FAILURE' "$report" || grep -q 'ERROR' "$report"; then
              cp "$report" "target/failed-test-reports/$(basename $report)"
            fi
          done

      - name: Debug failed test reports directory
        run: |
          echo "Contents of target/failed-test-reports directory:"
          ls -la target/failed-test-reports

      - name: Check for failed test reports
        run: |
          if [ -n "$(ls -A target/failed-test-reports)" ]; then
            echo "Failed tests found"
          else
            echo "No failed tests found, failing the job"
            exit 1
          fi

      - name: Upload failed test reports
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-reports
          path: target/failed-test-reports
          retention-days: 5
          if-no-files-found: warn


          
